[theme]

primaryColor = "#0d3d66"  # dark blue
backgroundColor = "#f2f2f2"  # light gray
secondaryBackgroundColor = "rgba(173, 216, 230, 0.5)"  # light blue
textColor = "#000000"  # black
font = "serif"

# Optional: Add a custom theme color for secondary text
[customTheme]
# secondaryTextColor = "#0d3d66"  # dark blue
