[theme]

primaryColor = "#00008b"  # dark blue
backgroundColor = "#f2f2f2"  # light gray
secondaryBackgroundColor = "#add8e6"  # light blue
textColor = "#000000"  # black
font = "serif"

# Optional: Add a custom theme color for secondary text
[customTheme]
# secondaryTextColor = "#00008b"  # dark blue

